language: c

sudo: true

env:
  global:
    # Git and Github credentials for pushing documentation
    - GIT_EMAIL=poppy-bot-ci@inria.fr
    - GIT_NAME=poppy-bot
    # GH_TOKEN encrypted below > travis encrypt GH_TOKEN=XXXXXX --add
    - secure: "DouAOOlgvhHqHE5fJDnOYaPdx4AN+oNLnxjzjKYeEdQxApt5fTyKaj5n9nuULVi6Ro0u7GiZ5nFsj+K0Lm/987ILPGO0Ba7o2jntXynvqYo906AhnmiPCJ4jKn76H3ufJR1Lw7Uyu8+OKfHiulpfx+6PnfouC3lzUmgSl+cuclQ="
    # COVERALLS_REPO_TOKEN not needed for travis
    # - secure: "jakEx084j88EtXmKb43lauyP3BiSEr67w"

matrix:
  include:
    - os: linux
      language: c
      env: SUITE=tests

    - os: linux
      language: c
      env: SUITE=build

install:
  - . ./ci/install.sh

script:
 - . ./ci/script.sh

after_success:
 - . ./ci/after_success.sh

notifications:
  email:
    - poppy-bot-ci@inria.fr
  on_failure: change
  on_success: change
